---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by satti.
--- DateTime: 2024/11/26 11:07
---
local voucherId=ARGV[1]
local userId=ARGV[2]

local stockKey='seckill:stock:' .. voucherId
local orderKey='seckill:order:' .. voucherId
--库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end
--是否重复下单
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2
end
-- 库存 下单
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
return 0